name: Commit

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
      - uses: actions/checkout@v3
      - name: Set up node 
        uses: actions/setup-node@v3.4.1
      - name: Install dependencies
        run: npm install
      - name: Run tests 
        run: npm test
